version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash

steps:
  - type: Command
    name: "Building golang webapp"
    command: |
      go build -o golangapp
    onFailure:                      # optional to handle any failure
      - type: Command
        command: |
          echo "Build failed"
        timeoutInSeconds: 400
        runAs: rootversion: 0.1

artifacts:
  files:
    - golangapp
    - buildspec.yml
