version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:

  exportedVariables:
    - version

steps:
  - type: Command
    name: "Running golang webapp"
    command: |
      go run main.go
    onFailure:                      # optional to handle any failure
      - type: Command
        command: |
          echo "Build failed"
        timeoutInSeconds: 400
        runAs: root
outputArtifacts:
  - name: go_app
    type: BINARY
    location: go_app.zip
